# Generated by Django 6.0.4 on 2026-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_badge_customuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cheat_meals_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cookie_container_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cookie_container_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='diet_tracker_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='freedom_passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quality_rating_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='🌱 The Beginner', max_length=80),
        ),
    ]
