# Generated by Django 6.0.5 on 2026-07-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_cheat_meals_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='boss_pending',
            field=models.BooleanField(default=False),
        ),
    ]
