# Generated by Django 6.0.4 on 2026-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='survive_threshold',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='win_threshold',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='task',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
