# Generated by Django 6.0.4 on 2026-05-12 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('age', models.PositiveIntegerField(default=25)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (No exercise)'), ('light', 'Light (1-2x/week)'), ('moderate', 'Moderate (3-4x/week)'), ('active', 'Active (5-6x/week)'), ('very_active', 'Very Active (2x/day)')], default='moderate', max_length=20)),
                ('physique_goal', models.CharField(choices=[('lean', 'Lean & Athletic'), ('cut', 'Weight Loss (Fat Cut)'), ('maintain', 'Maintain Physique'), ('bulk', 'Bulk (Mass Gain)'), ('custom', 'Custom Plan')], default='maintain', max_length=20)),
                ('daily_calories', models.IntegerField(default=2000)),
                ('protein_g', models.IntegerField(default=150)),
                ('carbs_g', models.IntegerField(default=250)),
                ('fat_g', models.IntegerField(default=65)),
                ('ai_plan', models.TextField(blank=True)),
                ('calorie_tolerance', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories_per_100', models.FloatField()),
                ('protein_per_100', models.FloatField(default=0)),
                ('carbs_per_100', models.FloatField(default=0)),
                ('fat_per_100', models.FloatField(default=0)),
                ('base_unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters'), ('pcs', 'Pieces'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon')], default='g', max_length=10)),
                ('ai_estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=15)),
                ('food_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.FloatField(default=100)),
                ('unit', models.CharField(default='g', max_length=10)),
                ('calories', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('is_cheat', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meal_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('has_cheat_meal', models.BooleanField(default=False)),
                ('day_status', models.CharField(choices=[('win', 'Goal Met'), ('survive', 'Close'), ('lose', 'Missed'), ('ongoing', 'Ongoing')], default='ongoing', max_length=10)),
                ('points_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
