# Generated by Django 6.0.7 on 2026-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='ai_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meallog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_photos/%Y/%m/%d/'),
        ),
    ]
