# Generated by Django 6.0.5 on 2026-07-10 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_dailylog_survive_threshold_dailylog_win_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(help_text="Matches the 'level' key in users.models.LEVELS")),
                ('name', models.CharField(max_length=100)),
                ('boss_type', models.CharField(choices=[('mini', 'Mini Boss'), ('final', 'Final Boss')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequence of mini bosses within the level')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bosses/')),
                ('hp', models.PositiveIntegerField(default=100)),
                ('tagline', models.CharField(blank=True, help_text="e.g. 'The weight that keeps you in bed'", max_length=150)),
            ],
            options={
                'ordering': ['level_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BossChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tasks.boss')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BossChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='tasks.bosschallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='BossDefeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeated_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeats', to='tasks.boss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_boss_defeats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'boss')},
            },
        ),
    ]
