# Generated by Django 6.0.5 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_boss_bosschallenge_bosschallengeprogress_bossdefeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='lore',
            field=models.TextField(blank=True, help_text="Shown in the info (i) tooltip — how this boss 'was born' and how to beat it."),
        ),
    ]
